
# Understanding Vectors, Matrices, and the Role of Linear Algebra



A vector is a mathematical entity used to represent physical quantities that have both magnitude and direction. It’s a fundamental tool for solving engineering and machine learning problems. So are matrices, which are used to represent vector transformations, among other applications.

Note: In Python, NumPy is the most used library for working with matrices and vectors. It uses a special type called ndarray to represent them. As an example, imagine that you need to create the following matrix:


\[
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{bmatrix}
\]



In [2]:
import numpy as np

A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

NumPy provides several functions to facilitate working with vector and matrix computations. 


As you may notice, NumPy provides a visual representation of the matrix, in which you can identify its columns and rows.

It’s worth noting that the elements of a NumPy array must be of the same type. You can check the type of a NumPy array using .dtype:

In [3]:
A.dtype

dtype('int64')

Because all the elements of A are integers, the array was created with type int64. If one of the elements is a float, then the array will be created with type float64:

In [4]:
B = np.array([[1.0, 2], [3, 4], [5, 6]])
print(B)
B.dtype

[[1. 2.]
 [3. 4.]
 [5. 6.]]


dtype('float64')

To check the dimensions of an ndarray object, you can use .shape. For example, to check the dimensions of A, you can use A.shape:

In [7]:
A.shape


(3, 2)

As expected, the dimensions of the A matrix are 3 × 2 since A has three rows and two columns.

When working with problems involving matrices, you’ll often need to use the transpose operation, which swaps the columns and rows of a matrix.

To transpose a vector or matrix represented by an ndarray object, you can use .transpose() or .T. For example, you can obtain the transpose of A with A.T:

In [8]:
print(A.T)
print(B.T)

[[1 3 5]
 [2 4 6]]
[[1. 3. 5.]
 [2. 4. 6.]]


With the transposition, the columns of A become the rows of A.T, and the rows become the columns.

To create a vector, you also use np.array(), providing a list with the elements of the vector:

In [9]:
v = np.array([1, 2, 3])
v

array([1, 2, 3])

To check the dimensions of the vector, you use .shape just like you did before:

In [10]:
v.shape

(3,)

Notice that the shape of this vector is (3,) and not (3, 1) or (1, 3).  In NumPy, it’s possible to create one-dimensional arrays such as v, which may cause problems when performing operations between matrices and vectors. For example, the transposition operation has no effect on one-dimensional arrays.

Whenever you provide a one-dimensional array-like argument to np.array(), the resulting array will be a one-dimensional array. To create a two-dimensional array, you must provide a two-dimensional array-like argument, such as a nested list:

In [13]:
v = np.array([[1], [2], [3]])
print(v)

v.shape

[[1]
 [2]
 [3]]


(3, 1)

In this case, the dimensions of v are 3 × 1, which corresponds to the dimensions of a two-dimensional column vector.

Using nested lists to create vectors can be laborious, especially for column vectors, which you’ll probably use the most. As an alternative, you can create a one-dimensional vector, providing a flat list to np.array, and use .reshape() to change the dimensions of the ndarray object:

In [14]:
v = np.array([1, 2, 3]).reshape(3, 1)
print(v)

[[1]
 [2]
 [3]]


In the above example, you use .reshape() to obtain a column vector with the shape (3, 1) from a one-dimensional vector with the shape (3,). It’s worth noting that .reshape() expects the number of elements of the new array to be compatible with the number of elements of the original array. In other words, the number of elements in the array with the new shape must be equal to the number of elements in the original array.

In this example, you could also use .reshape() without explicitly defining the number of rows of the array:

In [15]:
v = np.array([1, 2, 3]).reshape(-1, 1)
print(v)

[[1]
 [2]
 [3]]


Here, the -1 that you provide as an argument to .reshape() represents the number of rows necessary for the new array to have just one column, as specified by the second argument. In this case, because the original array has three elements, the number of rows for the new array will be 3.

# Using Convenience Functions to Create Arrays
NumPy also provides some convenience functions to create arrays. For example, to create an array filled with zeros, you can use np.zeros():

In [16]:
import numpy as np

np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

As its first argument, np.zeros() expects a tuple indicating the shape of the array that you want to create, and it returns an array of the type float64.

Note: To specify the type of array that np.zeros() will create, you can pass in an argument for dtype. For example, np.zeros((3, 2), dtype=int) creates an integer array.

It’s worth noting that np.ones() also returns an array of the type float64.

To create arrays with random elements, you can use np.random.rand():

In [24]:
np.random.randn(3, 2)

array([[ 0.38068349, -0.76567463],
       [ 0.39158015, -0.47697397],
       [-1.20311312, -0.96330425]])

Now that you’ve gone through creating arrays, you’ll see how to perform operations with them.

# Performing Operations on NumPy Arrays
The usual Python operations using the addition (+), subtraction (-), multiplication (*), division (/), and exponent (**) operators on arrays are always performed element-wise. If one of the operands is a scalar, then you’ll perform the operation between the scalar and each element of the array.

For example, to create a matrix filled with elements equal to 10, you can use np.ones() and multiply the output by 10 using the * operator:

In [29]:
np.ones((2, 2))
x = 10 * np.ones((2, 2))
print(x)

y = 20 *np.ones((2, 3))
print(y)

[[10. 10.]
 [10. 10.]]
[[20. 20. 20.]
 [20. 20. 20.]]


If both operands are arrays of the same shape, then you’ll perform the operation between the corresponding elements of the arrays:

In [31]:
A = np.array([[1, 2], [3, 4]])
print(A)

v = np.array([[5], [6]])
print(v)

A @ v

[[1 2]
 [3 4]]
[[5]
 [6]]


array([[17],
       [39]])

Here, you multiply each element of matrix A by the corresponding element of matrix B.

Here, you multiply a 2 × 2 matrix named A by a 2 × 1 vector named v.

You could obtain the same result using np.dot(), although you’re encouraged to use @ instead:

In [32]:
A = np.array([[1, 2], [3, 4]])
print(A)

v = np.array([[5], [6]])
print(v)

np.dot( A, v)

[[1 2]
 [3 4]]
[[5]
 [6]]


array([[17],
       [39]])


# Eigenvalues and Eigenvectors
Let's consider the matrix $\mathbf{A}$ and the vectors $\vec{u}$ and $\vec{v}$:

$$
\mathbf{A} =
\begin{pmatrix}
1 & 6 \\
5 & 2
\end{pmatrix}
~~~~~,~~~~~
\vec{u} =
\begin{pmatrix}
1 \\
1
\end{pmatrix}
~~~~~,~~~~~
\vec{v} =
\begin{pmatrix}
-6 \\
5
\end{pmatrix}
$$


By performing the $\mathbf{A}\vec{u}$ and $\mathbf{A}\vec{v}$ multiplications, we obtain that:

$$
\mathbf{A}\vec{u} =
\begin{pmatrix}
7 \\
7
\end{pmatrix}
~~~~~,~~~~~
\mathbf{A}\vec{v} =
\begin{pmatrix}
24 \\
-20
\end{pmatrix}
$$


Note that $\mathbf{A}\vec{u}=7\vec{u}$, and that $\mathbf{A}\vec{v}=-4\vec{v}$


<br>

An **eigenvector** of a ($n\times n$)-dimensional matrix $\mathbf{M}$ is a non-zero vector $\vec{x}$ such that $\mathbf{M}\vec{x}=\lambda\vec{x}$ for some scalar $\lambda$. A scalar $\lambda$ is an **eigenvalue** of $\mathbf{M}$ if there exists a non-trivial solution $\vec{x}$ of $\mathbf{M}\vec{x}=\lambda\vec{x}$; such $\vec{x}$ is the corresponding eigenvector of $\lambda$.

In quantum mechanics, and therefore in quantum computing, the eigenvectors are also called **eigenstates**.

<br>

From the previous example, notice that $7$ and $-4$ are the eigenvalues of $\mathbf{A}$ and their corresponding eigenvectors are $\vec{u}$ and $\vec{v}$.

<br>

# Linear Operators
An operator is generally a mapping or function that acts on elements of one space to produce elements of another space. A **linear operator** acts on _vector spaces_ and is mathematically written: $\mathbf{O}: U \rightarrow V$.

Where $\mathbf{O}$ is the map that sends the elements of the vector space $U$ to elements of the vector space $V$, both vector spaces must have the same field $F$ (for example, the real numbers or the complex numbers).

The most convenient way to understand linear operators is in termns of their **matrix representations**.

For example, consider the following operator $\mathbf{O}$, the vector space $U$ as the space of $3$-dimensional vectors, then one of its elements would be $\vec{u}$, and the vector space $V$ as the space of 2-dimensional vectors.

$$
\mathbf{O} =
\begin{pmatrix}
2 & -3 & 4 \\
1 & 7 & -5
\end{pmatrix}
~~~~~~,~~~~~~
\vec{u} =
\begin{pmatrix}
6 \\
-1 \\
2
\end{pmatrix}
$$


To find the mapping of $\mathbf{O}$ onto $\vec{u}$, we apply the operator on this vector, and we will obtain an element of the vector space $V$,

$$
\mathbf{O}\vec{u} = 
\begin{pmatrix}
2 & -3 & 4 \\
1 & 7 & -5
\end{pmatrix}
\begin{pmatrix}
6 \\
-1 \\
2
\end{pmatrix} = 
\begin{pmatrix}
23 \\
-11
\end{pmatrix} = \vec{v}
$$

where $\vec{v}$ is an element of $V$.

Let's consider the operator $R(\theta)$, this operator is parameterized, which means that it receives a parameter, a value that can change with each use of the operator.

$$
\mathbf{R(\theta)} = \begin{bmatrix}
\cos(\theta) & -\sin(\theta) \\
\sin(\theta) & \cos(\theta)
\end{bmatrix}
$$


Now, let's create a Python function that receives the parameter $\theta$ and returns the operator $R(\theta)$.

A **function** in programming is a block of code which only runs when it is called. You can pass data, known as parameters, into a function. A function can return data as a result.

Note that the values of the antidiagonal are very small, so they can be considered as zeros, so, when $\theta=\pi$ we have that,
$$
\mathbf{R(\pi)} = \begin{bmatrix}
-1 & 0 \\
0 & -1
\end{bmatrix}
$$



# Task 2 ASSIGNMENT
Create a function, called `applyOp`, which receives the operator $\mathbf{R(\theta)}$ and a 2-dimensional vector, internally applies $\mathbf{R(\theta)}$ to that vector, returning the result of that mapping.

$$
\mathbf{R(\theta)} = \begin{bmatrix}
\cos(\theta) & -\sin(\theta) \\
\sin(\theta) & \cos(\theta)
\end{bmatrix}
$$


Test your function with different values of $\theta$ and different vectors.



# Hermitian and Unitary Operators

An _complex square matrix_ $\mathbf{U}$, that is also [invertible](https://en.wikipedia.org/wiki/Invertible_matrix), is **unitary** if its conjugate transpose $\mathbf{U^*}$ is also its inverse ($\mathbf{U^{-1}}$), that is,


$$
\mathbf{U^*}\mathbf{U} = \mathbf{U}\mathbf{U^*} = \mathbf{U}\mathbf{U^{-1}} = \mathbf{I}
$$


where $\mathbf{I}$ is the identity matrix.

In quantum mechanics, the conjugate transpose is referred as the **Hermitian** of a matrix and is denoted with the dagger symbol ($\dagger$),

$$
\mathbf{U^*}\mathbf{U} = \mathbf{U}\mathbf{U^*} = \mathbf{U}\mathbf{U^{-1}} = \mathbf{I}
$$

This definition for matrices is extended to linear operators, calling them **unitary operators**. A unitary operator preserves the _lengths_ and _angles_ between vectors, and it can be considered as a type of rotation operator.


 # Task 3

Make a function that takes a parameter representing an matrix and returns `True` if the matrix is unitary, and `False` otherwise.

Use the `numpy` functions called [`allclose`](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) and [`eye`](https://numpy.org/devdocs/reference/generated/numpy.eye.html) (click on each one to go to its documentation).

Test your function with the matrices $\mathbf{M_1}$, $\mathbf{M_2}$ and $\mathbf{R(\theta)}$ with different values of $\theta$.


$$
\mathbf{M_1} = \begin{bmatrix}
\frac{1}{\sqrt{2}} & \frac{1}{\sqrt{2}} \\
\frac{1}{\sqrt{2}} & -\frac{1}{\sqrt{2}}
\end{bmatrix}
~~~~~,~~~~~
\mathbf{M_2} = \begin{bmatrix}
3 & 0 \\
0 & 3
\end{bmatrix}
~~~~~,~~~~~
\mathbf{R(\theta)} = \begin{bmatrix}
\cos(\theta) & -\sin(\theta) \\
\sin(\theta) & \cos(\theta)
\end{bmatrix}
$$




In [ ]:
from math import cos, sin, pi, sqrt
import numpy as np

def operatorR(theta):       # use of special word "def"
                            # receives the parameter called "theta", a variable

    R = np.array([[cos(theta), -sin(theta)],
                  [sin(theta),  cos(theta)]])

    return R                # returns the R(theta) operator in matrix form for the specified "theta" value

# Tensor Product
The **tensor product**, denoted by $\otimes$, is an operation between elements of two vector spaces, although it can be the same vector space for both factors.

If the factors are matrices, then it is known as the **Kronecker product** and in general it behaves like this:

$$
\mathbf{A} \otimes \mathbf{B} = \begin{bmatrix}
a_{11}\mathbf{B} & \cdots & a_{1n}\mathbf{B} \\
\vdots & \ddots & \vdots \\
a_{m1}\mathbf{B} & \cdots & a_{mn}\mathbf{B}
\end{bmatrix}
$$

where $a_{ij}$ are the elements of the matrix $\mathbf{A}$.

